version: '3'

services:
    diagram_webservice:
        build:
            context: ./back/diagram_webservice
            dockerfile: dockerfile
        environment:
            - PRODUCTION_VARIABLES=1
        volumes:
            - ./resources:/usr/resources
        networks:
            - "net"
        ports:
            - "8000:8000"

    front_vue:
        build:
            context: ./front/diagram_display
            dockerfile: dockerfile
        restart: always
        networks:
            - "net"
        environment:
            - PRODUCTION_VARIABLES=1
            - VUE_APP_RESOURCES_DIRECTORY="/usr/resources"
        ports:
            - "80:8080"
        volumes:
            - ./resources:/usr/resources
        
networks:
    net:
        driver: "bridge"
