version: '3'
services:
  dsc_suicide_redis:
    container_name: dsc_suicide_redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - "net"

  dsc_suicide_redis-commander:
    container_name: dsc_suicide_redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - "net"

        
networks:
    net:
        driver: "bridge"
