version: '3'

services:
    diagram_webservice:
        build:
            context: ./back/diagram_webservice
            dockerfile: dockerfile
        container_name: diagram_webservice
        environment:
            - DSC_SUICIDE_PRODUCTION_VARIABLES=1
            - REDIS_HOST=dsc_suicide_redis
            - REDIS_PORT=6379
            - REDIS_DB=0
        volumes:
            - ./resources:/usr/resources
        networks:
            - "net"
        ports:
            - "8000:8000"

    front_vue:
        build:
            context: ./front/diagram_display
            dockerfile: dockerfile
        restart: always
        environment:
            - DSC_SUICIDE_PRODUCTION_VARIABLES=1
        ports:
            - "80:8080"
        volumes:
            - ./resources:/resources
        networks:
            - "net"
    
    dsc_suicide_redis:
        container_name: dsc_suicide_redis
        hostname: redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
            - ./data/conf:/usr/local/etc/redis

        environment:
            - CONTAINERIZED_VARIABLES=1
        networks:
            - "net"
  
networks:
    net:
        driver: "bridge"
