version: '3'

services:
    diagram_webservice:
        build:
            context: ./back/diagram_webservice
            dockerfile: dockerfile
        environment:
            - DSC_SUICIDE_PRODUCTION_VARIABLES=1
            - REDIS_HOST = mutezone.site
            - REDIS_PORT = 6379
            - REDIS_DB = 0
        volumes:
            - ./resources:/usr/resources
        networks:
            - "net"
        ports:
            - "8000:8000"

    front_vue:
        build:
            context: ./front/diagram_display
            dockerfile: dockerfile
        restart: always
        networks:
            - "net"
        environment:
            - DSC_SUICIDE_PRODUCTION_VARIABLES=1
        ports:
            - "80:8080"
        volumes:
            - ./resources:/resources
        
networks:
    net:
        driver: "bridge"
