version: '3'

services:
    diagram_webservice:
        build:
            context: ./back/diagram_webservice
            dockerfile: dockerfile
        networks:
            - "net"
        ports:
            - "8000:8000"

    front_vue:
        build:
            context:
                ./front/diagram_display
            dockerfile: dockerfile
        networks:
            - "net"
        ports:
            - "8080:80"
        

    
networks:
    net:
        driver: "bridge"
