version: '3'

services:
    diagram_webservice:
        build:
            context: ./back/diagram_webservice
            dockerfile: dockerfile
        expose: 
            - 8000
    
    nginx:
        build:
            context: ./services/nginx
            dockerfile: dockerfile
        ports:
            - 1337:80
        depends_on:
            - diagram_webservice
        