from numpy import log
from utils.aliases import DATASETS, OUT_DIR
import utils.file_handling as file_handler
import pandas as pd
import matplotlib.pyplot as plt


def prepare_sdg():
    df = pd.read_csv(DATASETS.get("sdg"))

    # The format of this file is weird, in the way, that it comes with two headers.
    # Where in the first row is the second header.
    # See file for 1st header

    header = df.iloc[0]
    df = df[1:]
    df.columns = header
    return df


# Simplifying list comprehension
def _is_digit_and_is_between_range(column, min, max):
    if column.isdigit():
        if int(column) < min or int(column) > max:
            return True
    return False


# prototype
def basic_sdg(min_date=2000, max_date=2019):
    # Files are generated by their name.
    # If a file in the out directory already contains a file by the generated name,
    # then the function will not be called to save processing power.
    file_name = file_handler.generate_file_name(
        "sdg_basic", min_date, max_date)
    if file_name == False:
        return
    df = prepare_sdg()
    df = df.drop(columns=[column for column in df.columns if _is_digit_and_is_between_range(
        column, min_date, max_date)], axis=1)

    df = df[df["WHO region"] == "Global"]
    df.drop(columns=["WHO region"], inplace=True)
    df = df.T

    header = df.iloc[0]
    df = df[1:]
    df.columns = header

    plt.bar(df['Male'], df['Female'])
    plt.savefig(f"{OUT_DIR}/{file_name}.png")
