FROM nginx:1.17-alpine


RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/
RUN rm /etc/nginx/sites-enabled/reverse-proxy.conf
COPY reverse-proxy.conf /etc/nginx/sites-enabled/

# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/