FROM python:3.9.4-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . .

# Change this to gunicorn after testing period.

CMD ["gunicorn","--chdir","src","main:app" ]