FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Change this to gunicorn after testing period.
EXPOSE 5000


CMD [ "python", "./src/main.py" ]