FROM python:3.9.4-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY . .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends netcat

EXPOSE 8000

CMD ["gunicorn","--chdir","src","main:app","-b","0.0.0.0:8000"]