name: Deploy

on:
  push:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deleting current contents of remote repository
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MUTEZONE_HOST }}
        USERNAME: ${{ secrets.MUTEZONE_USERNAME }}
        PASSPHRASE: ${{ secrets.MUTEZONE_PASSPHRASE }}
        PORT: ${{ secrets.MUTEZONE_PORT }}
        KEY: ${{ secrets.MUTEZONE_SSHKEY }}
        script: |
          cd ~/deployment
          shopt -s extglob
          rm -rf !("resources"|"data")

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.MUTEZONE_HOST }}
        USERNAME: ${{ secrets.MUTEZONE_USERNAME }}
        PASSPHRASE: ${{ secrets.MUTEZONE_PASSPHRASE }}
        PORT: ${{ secrets.MUTEZONE_PORT }}
        KEY: ${{ secrets.MUTEZONE_SSHKEY }}
      with:
        source: "."
        target: "~/deployment"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MUTEZONE_HOST }}
        USERNAME: ${{ secrets.MUTEZONE_USERNAME }}
        PASSPHRASE: ${{ secrets.MUTEZONE_PASSPHRASE }}
        PORT: ${{ secrets.MUTEZONE_PORT }}
        KEY: ${{ secrets.MUTEZONE_SSHKEY }}
        script: |
          cd ~/deployment
          docker-compose up --build -d



